# Generated by Django 4.1.1 on 2022-09-15 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=45)),
                ('fecha_Nacimiento', models.DateField()),
                ('latitud', models.CharField(max_length=50)),
                ('longitud', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('telefono', models.BigIntegerField()),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_signo_vital', models.CharField(max_length=70)),
                ('valor_signo_vital', models.CharField(max_length=45)),
                ('fecha', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaAPI.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaAPI.persona'),
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=45)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaAPI.paciente')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaAPI.persona')),
                ('signos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaAPI.signosvitale')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(choices=[('F', 'Padre/Madre'), ('S', 'Hijo/Hija'), ('B', 'Hermano/Hermana'), ('G', 'Abuelo/Abuela'), ('O', 'Otro')], default='F', max_length=1)),
                ('e_mail', models.EmailField(max_length=45)),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaAPI.paciente')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaAPI.persona')),
            ],
        ),
        migrations.CreateModel(
            name='EnfermeroAux',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaAPI.paciente')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaAPI.persona')),
                ('signos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaAPI.signosvitale')),
            ],
        ),
    ]
