# Generated by Django 4.1.1 on 2022-09-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaAPI', '0002_alter_paciente_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_Nacimiento',
            field=models.CharField(max_length=15),
        ),
    ]
