# Generated by Django 4.1.1 on 2022-09-16 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaAPI', '0006_rename_id_paciente_paciente_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaAPI.persona'),
        ),
    ]
