# Generated by Django 4.1.1 on 2022-09-17 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaAPI', '0007_alter_paciente_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='persona',
        ),
    ]
