# Generated by Django 4.1.1 on 2022-09-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaAPI', '0008_remove_paciente_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
