# Generated by Django 4.1.1 on 2022-09-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaAPI', '0012_alter_enfermeroaux_persona_alter_familiar_persona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signosvitale',
            name='fecha',
            field=models.CharField(max_length=15),
        ),
    ]
