# Generated by Django 4.1.1 on 2022-09-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaAPI', '0013_alter_signosvitale_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('contrase', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='familiar',
            name='e_mail',
            field=models.EmailField(max_length=254),
        ),
    ]
