# Generated by Django 4.1.1 on 2022-10-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaAPI', '0015_alter_familiar_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='parentesco',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
